services:
  postgres:
    image: postgres:16.3-alpine
    env_file: .env
    volumes:
      - postgres-data-16:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1"]
      interval: 20s
      timeout: 3s
      retries: 5
      start_period: 20s
    ports:
      - "5432:5432"

volumes:
  postgres-data-16:
